name: topology_cpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - seaborn
  - jupyter
  - jupyterlab
  - ipykernel
  - notebook
  - ipython
  - ipywidgets
  - plotly
  - pyyaml
  - pip:
      # PyTorch CPU version
      - torch>=2.0.0 --index-url https://download.pytorch.org/whl/cpu
      - torchvision --index-url https://download.pytorch.org/whl/cpu
      - torchaudio --index-url https://download.pytorch.org/whl/cpu
      
      # CEBRA and neural analysis
      - cebra==0.5.0
      
      # Topological Data Analysis
      - ripser==0.6.12
      - persim==0.3.8
      - gudhi>=3.8.0
      - giotto-tda==0.6.2
      
      # Dimensionality reduction and clustering
      - umap-learn==0.5.7
      - pynndescent
      
      # Additional scientific computing
      - tqdm
      - requests
      - joblib
      - threadpoolctl
      - numba
      - llvmlite
      
      # Visualization enhancements
      - matplotlib-inline
      - ipython-pygments-lexers
      
      # Utility packages
      - deprecated
      - hopcroftkarp
      - texttable
      - igraph
      - pyflagser
      - giotto-ph
      - wrapt
      - literate-dataclasses
prefix: /opt/anaconda3/envs/topology_cpu
